service: ts-base
provider:
  name: aws
  runtime: nodejs12.x
custom:
  functionsBasePath: src
plugins:
  - serverless-functions-base-path
  - serverless-plugin-typescript
  - serverless-offline
functions:
  ping:
    handler: ping/ping.pong
    events:
      - http: GET ping